name: Alex Dukhno

description: Software Engineer

avatar: https://avatars2.githubusercontent.com/u/5074607?v=3&s=460

footer-links:
  email: alex.dukhno@icloud.com
  github: Alex-Diez
  linkedin: oleksandr-alex-duhno-41181723
  twitter: AlexanderDukhno

baseurl: ""

permalink: /:title/
markdown:  kramdown
version:   v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :expanded

gems:
  - jemoji

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
